### PR TITLE
feat(logging): add structured logging

### PR DESCRIPTION
**Pull request by Phil91**
adding serilog to provide structured logging as a json for a better searchability for grafana

Refs: CPLP-1849

### CODE REVIEW

**Comment by Phil91** [comment]
@ntruchsess the current implementation of the logging is using the configuration to setup how the logger should log things. another possibility is to do that with a fluent api in the code. We glady can discuss about that.

The sonar cloud security hotspot isn't a problem in my opinion, please let me know if you think otherwise.

**Comment by evegufy** [comment]
@Phil91 did you notice the security hotspots? https://sonarcloud.io/project/security_hotspots?id=catenax-ng_tx-portal-backend&pullRequest=377&resolved=false&types=SECURITY_HOTSPOT

**Comment by Phil91** [comment]
> @Phil91 did you notice the security hotspots? https://sonarcloud.io/project/security_hotspots?id=catenax-ng_tx-portal-backend&pullRequest=377&resolved=false&types=SECURITY_HOTSPOT

@evegufy I did see it, in my opinion it's safe and exactly what sonar suggests as fix, I'd like to hear Norberts opinion on that. If he agrees with me I'd comment the 2 findings and mark them as won't fix or something like that.

**Comment by evegufy** [comment]
I created the following license review requests:
https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/8433.
A review is required for nuget/nuget/-/Serilog.Sinks.Console/4.1.0.
https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/8434.
A review is required for nuget/nuget/-/Serilog/2.12.0.
https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/8435.
A review is required for nuget/nuget/-/Serilog.Extensions.Hosting/5.0.1.
https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/8436.
A review is required for nuget/nuget/-/Serilog.AspNetCore/6.1.0.
https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/8437.
A review is required for nuget/nuget/-/xunit/2.4.1.
https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/8438.

**Comment by evegufy** [comment]
> I created the following license review requests: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/8433. A review is required for nuget/nuget/-/Serilog.Sinks.Console/4.1.0. https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/8434. A review is required for nuget/nuget/-/Serilog/2.12.0. https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/8435. A review is required for nuget/nuget/-/Serilog.Extensions.Hosting/5.0.1. https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/8436. A review is required for nuget/nuget/-/Serilog.AspNetCore/6.1.0. https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/8437. A review is required for nuget/nuget/-/xunit/2.4.1. https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/8438.

All ip requests have been approved.

**Comment by ntruchsess** [comment]
obsoleted by https://github.com/eclipse-tractusx/portal-backend/pull/52

**Pull request closed without merging**
