### PR TITLE
fix: cplp-1042 - add data to seeding e.g. iam_identity_providers

### PR DESCRIPTION
**Pull request by evegufy**
https://jira.catena-x.net/browse/CPLP-1042

### CODE REVIEW

**Review by jjeroch — APPROVED** [review]

**Comment by evegufy** [comment]
@Phil91 Could you please have a quick check after your vacation?

**Review by Phil91 — APPROVED** [review]
@evegufy looks fine to me, are the added files supposed to be empty?

**Comment by evegufy** [comment]
> @evegufy looks fine to me, are the added files supposed to be empty?

Thank you! Yes, they are supposed to be empty, every file available under Seeder/Data should be in enabled for seeding as I don't find it intuitiv when the file is there but not enabled also for the most part they'll needed to be filled soon.

How did you decide whether to add the table to seeding via BaseEntityBatchSeeder class or via MappingEntityInsertOnlySeeder class?
To add the tables to MappingEntityInsertOnlySeeder was a bit of a gut feeling...

**Comment by Phil91** [comment]
> > @evegufy looks fine to me, are the added files supposed to be empty?
> 
> Thank you! Yes, they are supposed to be empty, every file available under Seeder/Data should be in enabled for seeding as I don't find it intuitiv when the file is there but not enabled also for the most part they'll needed to be filled soon.
> 
> How did you decide whether to add the table to seeding via BaseEntityBatchSeeder class or via MappingEntityInsertOnlySeeder class? To add the tables to MappingEntityInsertOnlySeeder was a bit of a gut feeling...

@evegufy the decision on where to put it can be made pretty quickly. If the entity has an Id Property of type GUID and we want batch updating functionality, we would put it into BaseEntityBatchSeeder, if it has a combined key, e.g. CompanyServiceAccountAssignedRole and we don't want to have batch updating functionality, instead we always want to add the data in the JSON to the database we would use the MappingEntityInsertOnlySeeder. As soon as we have an entity with a combined key like CompanyServiceAccountAssignedRole and we want to do something special we would need a separate implementation of ICustomSeeder.

As an explanation of why IamServiceAccount and IamIdentityProvider are not in the BaseEntityBatchSeeder, both entities don't have a combined key, but per definition, we do a select on the Id column of an entity, both IamServiceAccount and IamIdentityProvider don't have an Id column, so we'd either need to rename the PrimaryKey Column of the entities, or use the MappingEntityInsertOnlySeeder 😄 

For future improvement, I am planning to refactor the logic a bit, so that we only need one seeder which handles the selection of the database and inserts only the new values for us.

**Pull request merged**
