### PR TITLE
DB Seeding_Add agreement data upload

### PR DESCRIPTION
**Pull request by jjeroch**

### CODE REVIEW

**Review by Phil91 — APPROVED** [review]
Seeding is working, but recognized that the Security Regulations - Active Participant agreement was deleted, was it accidental or intentional?

**Comment by jjeroch** [comment]
> Member

Oh that seems to be an accidental delete. I will add it again.

**Comment by jjeroch** [comment]
> Seeding is working, but recognized that the Security Regulations - Active Participant agreement was deleted, was it accidental or intentional?
Oh that seems to be an accidental delete. I will add it again.

**Review by Phil91 — APPROVED** [review]

**Comment by Phil91** [comment]
@jjeroch i will merge the pr as soon as #51 is merged because this PR builds on the other one

**Pull request merged**
