### PR TITLE
feat(app): get appdocument(pdf) refactoring

### PR DESCRIPTION
**Pull request by qxz2mqe**
Enhanced end point  /api/apps/{appId}/appImages/{documentId}  to support additional document type of pdf
Refs: CPLP-2268

### CODE REVIEW

**Comment by Phil91** [comment]
@qxz2mqe please create and link the PR in the CD Repository for the config changes

**Comment by qxz2mqe** [comment]
@Phil91 PR for CD changes was created and merged. For your reference https://github.com/catenax-ng/tx-portal-cd/pull/42

**Comment by qxz2mqe** [comment]
@jjeroch Please Confirm because the existing end point also we were not filtering it based on  document status. If require this then we have to create a new endpoint in this case.

**Comment by ntruchsess** [comment]
> @jjeroch Please Confirm because the existing end point also we were not filtering it based on document status. If require this then we have to create a new endpoint in this case.

I did talk to @jjeroch and we agreed to return everything except INACTIVE documents (in this endpoint). I did add this filter to the query and businesslogic.

**Review by ntruchsess — APPROVED** [review]

**Pull request merged**
