### PR TITLE
Seeding/add service accounts base image

### PR DESCRIPTION
**Pull request by jjeroch**
- service account assigned roles deleted since the roles where wrong
- service account table enhanced with new technical user and meaningful description added
- iam_service_account table filled to enable connect to Keycloak

### CODE REVIEW

**Comment by jjeroch** [comment]
@Phil91  unit tests are failing, maybe because of expected data in the service_account_assigned_role table. Can you help and look into the details?

**Comment by Phil91** [comment]
> @Phil91 unit tests are failing, maybe because of expected data in the service_account_assigned_role table. Can you help and look into the details?

@jjeroch will have a look at it now

**Review by Phil91 — APPROVED** [review]
successfully tested locally

**Comment by Phil91** [comment]
@jjeroch just to let you know, i've added a process_steps.consortia and application_assigned_process_steps.consortia file with content to have the application_checklist items setup correctly

**Pull request merged**
