### PR TITLE
feat(process): add process for offerSubscription

### PR DESCRIPTION
**Pull request by Phil91**
add process for the offer subscription and auto setup process
add new subscription configuration endpoint

Refs: CPLP-2443, CPLP-2344
BREAKING CHANGE: Move ServiceProvider Endpoints to new SubscriptionConfiguration Endpoint
[CD-Pr](https://github.com/catenax-ng/tx-portal-cd/pull/64)

### CODE REVIEW

**Comment by nidhigarg-bmw** [comment]
@ntruchsess @qxz2mqe I want this PR to be merged quickly as have some tasks related to this on FE

**Comment by jjeroch** [comment]
@Phil91 are we running in troubles with the conflicts?

**Comment by Phil91** [comment]
> @Phil91 are we running in troubles with the conflicts?

@jjeroch I'll rebase dev into the branch than everything should be fine

**Review by ntruchsess — APPROVED** [review]
re-review after adding more unit-tests

**Comment by Phil91** [comment]
This PR was merged to upstream within: https://github.com/eclipse-tractusx/portal-backend/pull/37

**Pull request closed without merging**
